### ISSUE TITLE
Log does not display in real time

### ISSUE THREAD

**Issue by Dovahkiin-Warrior** [Holinhed-Studio/youtube-dl-ui#2]
* Expected Behavior: YTDLGUI should show the log in real time
* Actual Behavior: YTDLGUI does not show the log in real time
* Provide Screenshots:
![image](https://user-images.githubusercontent.com/16886014/60387861-cb0e2b80-9a77-11e9-8367-478345835bbd.png)

**Comment by HOLINHED** [comment]
This is currently expected behavior until eventlog is fully implemented.

**Comment by Dovahkiin-Warrior** [comment]
Right-eo.
